import { AIRLINE_ALLIANCES, ALL_AIRLINES, AIRCRAFT_MODELS, AIRCRAFT_FAMILIES, getAircraftBlueprint } from '../data/airlineData.js';
export { AIRLINE_ALLIANCES, ALL_AIRLINES, AIRCRAFT_MODELS, AIRCRAFT_FAMILIES, getAircraftBlueprint };
import confetti from 'canvas-confetti';
import { TURKEY_PROVINCES } from '../data/turkeyData.js';
import { WORLD_COUNTRIES, TOTAL_WORLD_COUNTRIES_BENCHMARK } from '../data/worldData.js';
import { calculateDemographicImpact } from '../data/worldDemographics.js';
import { deletePhotosByTarget } from './photoStorage.js';
import { queueCloudSync, getSyncStatus, onSyncStatusChange, fetchAndMergeUserDataFromCloud } from '../services/syncService.js';
export { queueCloudSync, getSyncStatus, onSyncStatusChange, fetchAndMergeUserDataFromCloud };

export const STORAGE_KEYS = {
  TURKEY_VISITS: 'gittigim_yerler_turkey_v2',
  WORLD_VISITS: 'gittigim_yerler_world_v2',
  WORLD_CITIES: 'gittigim_yerler_cities_v2',
  USER_PROFILE: 'gittigim_yerler_profile_v2',
  BUCKET_RANKS: 'gittigim_yerler_bucket_ranks_v1',
  USER_AIRLINES: 'gittigim_yerler_airlines_v1',
  USER_AIRCRAFT: 'gittigim_yerler_aircraft_v1',
  SAVED_FRIENDS: 'gittigim_yerler_saved_friends_v1',
  USER_FEEDBACKS: 'gv_user_feedbacks_v1',
  FEEDBACK_STATUS_OVERRIDES: 'gv_feedback_status_overrides_v1',
  HOME_COUNTRY: 'gv_home_country'
};

function safeSetItem(key, value) {
  try {
    localStorage.setItem(key, value);
  } catch (e) {
    console.warn('LocalStorage save error for key:', key, e);
    if (e && (e.name === 'QuotaExceededError' || e.code === 22 || e.code === 1014 || e.number === -2147024882)) {
      if (typeof window !== 'undefined' && !window.__lastQuotaAlert) {
        window.__lastQuotaAlert = true;
        setTimeout(() => { window.__lastQuotaAlert = false; }, 30000);
        if (typeof alert !== 'undefined') {
          alert('Tarayıcı depolama alanı dolmak üzere veya doldu. Lütfen Ayarlar sekmesinden yedek alıp gereksiz verileri temizleyiniz.');
        }
      }
    }
  }
}

export function isAutoGeneratedNote(note) {
  if (!note || typeof note !== 'string') return false;
  const lower = note.toLowerCase().trim();
  return lower.startsWith('auto-marked') ||
         lower.includes('otomatik işaretlendi') ||
         lower.includes('şehir ziyareti') ||
         lower.includes('alt bölge ziyareti');
}

export function cleanNote(note) {
  return isAutoGeneratedNote(note) ? '' : (note || '');
}

// Store default initial state
export function getStorageData() {
  let turkeyVisits = {};
  let worldVisits = {};
  let worldCities = [];
  let userProfile = { name: 'Gezgin', bio: 'Dünyayı keşfediyorum!' };

  try {
    const rawTurkey = localStorage.getItem(STORAGE_KEYS.TURKEY_VISITS);
    if (rawTurkey) {
      const p = JSON.parse(rawTurkey);
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        turkeyVisits = p;
        for (const k in turkeyVisits) {
          if (turkeyVisits[k]) {
            if (isAutoGeneratedNote(turkeyVisits[k].notes)) turkeyVisits[k].notes = '';
            if (turkeyVisits[k].journal && isAutoGeneratedNote(turkeyVisits[k].journal.text)) turkeyVisits[k].journal.text = '';
          }
        }
      }
    }

    const rawWorld = localStorage.getItem(STORAGE_KEYS.WORLD_VISITS);
    if (rawWorld) {
      const p = JSON.parse(rawWorld);
      if (p && typeof p === 'object' && !Array.isArray(p)) {
        worldVisits = p;
        for (const k in worldVisits) {
          if (worldVisits[k]) {
            if (isAutoGeneratedNote(worldVisits[k].notes)) worldVisits[k].notes = '';
            if (worldVisits[k].journal && isAutoGeneratedNote(worldVisits[k].journal.text)) worldVisits[k].journal.text = '';
          }
        }
      }
    }

    const rawCities = localStorage.getItem(STORAGE_KEYS.WORLD_CITIES);
    if (rawCities) {
      const p = JSON.parse(rawCities);
      if (Array.isArray(p)) worldCities = p;
    }

    const rawProfile = localStorage.getItem('gv_profile') || localStorage.getItem(STORAGE_KEYS.USER_PROFILE);
    if (rawProfile) {
      const parsed = JSON.parse(rawProfile);
      if (parsed && typeof parsed === 'object') userProfile = parsed;
    }
  } catch (err) {
    console.error('Error loading LocalStorage:', err);
  }

  return { turkeyVisits, worldVisits, worldCities, userProfile };
}

export function saveTurkeyVisit(provinceId, status, details = {}) {
  const { turkeyVisits } = getStorageData();
  if (status === 'unvisited' || !status) {
    delete turkeyVisits[provinceId];
    deletePhotosByTarget('TR::' + provinceId).catch(() => {});
    deletePhotosByTarget(String(provinceId)).catch(() => {});
  } else {
    const existing = turkeyVisits[provinceId] || {};
    const wasAlreadyVisited = existing && existing.status === 'visited';
    const isVisited = status === 'visited';
    const autoEntryDate = isVisited ? new Date().toISOString().split('T')[0] : '';
    const autoTransport = isVisited ? 'car' : '';
    const cleanNotesVal = cleanNote(details.notes !== undefined ? details.notes : (existing.notes || ''));
    turkeyVisits[provinceId] = {
      status,
      date: details.date || existing.date || new Date().toISOString().split('T')[0],
      notes: cleanNotesVal,
      rating: details.rating !== undefined ? details.rating : (existing.rating || 0),
      entryDate: details.entryDate ? details.entryDate : (existing.entryDate || autoEntryDate),
      entryTransport: details.entryTransport ? details.entryTransport : (existing.entryTransport || autoTransport),
      exitDate: details.exitDate !== undefined ? details.exitDate : (existing.exitDate || ''),
      exitTransport: details.exitTransport !== undefined ? details.exitTransport : (existing.exitTransport || ''),
      buddies: details.buddies !== undefined ? details.buddies : (existing.buddies || []),
      places: details.places !== undefined ? details.places : (existing.places || []),
      journal: details.journal !== undefined ? details.journal : (existing.journal || null)
    };
    if (status === 'visited' && !wasAlreadyVisited) {
      triggerConfetti();
    }
  }
  safeSetItem(STORAGE_KEYS.TURKEY_VISITS, JSON.stringify(turkeyVisits));

  // Two-way synchronization with Turkey (TR) country status
  syncCountryFromSubdivision('TR', status);

  notifyStateChange();
}

export function syncCountryFromSubdivision(countryCode, subStatus) {
  if (!countryCode) return;
  const { worldVisits } = getStorageData();
  const currentCountry = worldVisits[countryCode] || {};
  const currentStatus = currentCountry.status || 'unvisited';

  if (subStatus === 'visited') {
    if (currentStatus !== 'visited') {
      worldVisits[countryCode] = {
        ...currentCountry,
        status: 'visited',
        date: currentCountry.date || new Date().toISOString().split('T')[0],
        notes: cleanNote(currentCountry.notes)
      };
      safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(worldVisits));
    }
  } else if (subStatus === 'planned') {
    // Only upgrade to planned if not already visited
    if (currentStatus !== 'visited' && currentStatus !== 'planned') {
      worldVisits[countryCode] = {
        ...currentCountry,
        status: 'planned',
        date: currentCountry.date || new Date().toISOString().split('T')[0]
      };
      safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(worldVisits));
    }
  } else if (subStatus === 'wishlist') {
    // Only upgrade to wishlist if unvisited
    if (currentStatus === 'unvisited' || !currentStatus) {
      worldVisits[countryCode] = {
        ...currentCountry,
        status: 'wishlist',
        date: currentCountry.date || new Date().toISOString().split('T')[0]
      };
      safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(worldVisits));
    }
  }
}

export function saveWorldVisit(countryCode, status, details = {}) {
  const { worldVisits } = getStorageData();
  if (status === 'unvisited' || !status) {
    delete worldVisits[countryCode];
    deletePhotosByTarget(String(countryCode)).catch(() => {});
  } else {
    const existing = worldVisits[countryCode] || {};
    const isVisited = status === 'visited';
    const autoEntryDate = isVisited ? new Date().toISOString().split('T')[0] : '';
    const autoTransport = isVisited ? ((countryCode === 'TR' || countryCode.startsWith('TR::')) ? 'car' : 'flight') : '';
    
    // Multi-visit array preservation & synchronization
    let visits = details.visits;
    let featuredIdx = details.featuredVisitIndex !== undefined 
      ? details.featuredVisitIndex 
      : (existing.featuredVisitIndex !== undefined ? existing.featuredVisitIndex : 0);

    if (!Array.isArray(visits) || visits.length === 0) {
      if (Array.isArray(existing.visits) && existing.visits.length > 0) {
        visits = [...existing.visits];
        // If entry/exit details passed, update the currently featured visit
        const fv = visits[featuredIdx] || visits[0];
        if (fv) {
          if (details.entryDate !== undefined) fv.entryDate = details.entryDate;
          if (details.entryTransport !== undefined) fv.entryTransport = details.entryTransport;
          if (details.exitDate !== undefined) fv.exitDate = details.exitDate;
          if (details.exitTransport !== undefined) fv.exitTransport = details.exitTransport;
          if (details.buddies !== undefined) fv.buddies = details.buddies;
        }
      } else if (isVisited) {
        visits = [{
          id: 'v_init',
          entryDate: details.entryDate || existing.entryDate || autoEntryDate,
          entryTransport: details.entryTransport || existing.entryTransport || autoTransport,
          exitDate: details.exitDate !== undefined ? details.exitDate : (existing.exitDate || ''),
          exitTransport: details.exitTransport !== undefined ? details.exitTransport : (existing.exitTransport || autoTransport),
          buddies: details.buddies !== undefined ? details.buddies : (existing.buddies || [])
        }];
      } else {
        visits = [];
      }
    }

    const safeFeaturedIdx = visits.length > 0 ? Math.max(0, Math.min(visits.length - 1, featuredIdx)) : 0;
    const featuredVisit = visits[safeFeaturedIdx] || {};

    const wasAlreadyVisited = existing && existing.status === 'visited';
    const cleanNotesVal = cleanNote(details.notes !== undefined ? details.notes : (existing.notes || ''));

    worldVisits[countryCode] = {
      status,
      date: details.date || existing.date || featuredVisit.entryDate || new Date().toISOString().split('T')[0],
      notes: cleanNotesVal,
      rating: details.rating !== undefined ? details.rating : (existing.rating || 0),
      entryDate: details.entryDate ? details.entryDate : (featuredVisit.entryDate || existing.entryDate || autoEntryDate),
      entryTransport: details.entryTransport ? details.entryTransport : (featuredVisit.entryTransport || existing.entryTransport || autoTransport),
      exitDate: details.exitDate !== undefined ? details.exitDate : (featuredVisit.exitDate !== undefined ? featuredVisit.exitDate : (existing.exitDate || '')),
      exitTransport: details.exitTransport !== undefined ? details.exitTransport : (featuredVisit.exitTransport !== undefined ? featuredVisit.exitTransport : (existing.exitTransport || '')),
      buddies: details.buddies !== undefined ? details.buddies : (featuredVisit.buddies !== undefined ? featuredVisit.buddies : (existing.buddies || [])),
      places: details.places !== undefined ? details.places : (existing.places || []),
      journal: details.journal !== undefined ? details.journal : (existing.journal || null),
      visits,
      featuredVisitIndex: safeFeaturedIdx
    };
    if (status === 'visited' && !wasAlreadyVisited) {
      triggerConfetti();
    }
  }
  safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(worldVisits));

  // If this is a region/subregion (contains '::'), synchronize with parent country
  if (countryCode.includes('::')) {
    const parentCode = countryCode.split('::')[0];
    syncCountryFromSubdivision(parentCode, status);
  }

  notifyStateChange();
}

export function getCountryVisits(countryCode) {
  const { worldVisits } = getStorageData();
  const visit = worldVisits[countryCode];
  if (!visit || visit.status !== 'visited') return [];
  if (Array.isArray(visit.visits) && visit.visits.length > 0) {
    return visit.visits;
  }
  return [{
    id: 'v_default',
    entryDate: visit.entryDate || visit.date || '',
    entryTransport: visit.entryTransport || (countryCode === 'TR' ? 'car' : 'flight'),
    exitDate: visit.exitDate || '',
    exitTransport: visit.exitTransport || visit.entryTransport || 'flight',
    buddies: Array.isArray(visit.buddies) ? visit.buddies : []
  }];
}

export function saveCountryVisits(countryCode, visitsList, featuredIndex = 0) {
  const { worldVisits } = getStorageData();
  const existing = worldVisits[countryCode] || { status: 'visited' };
  const safeVisits = Array.isArray(visitsList) && visitsList.length > 0 ? visitsList : [];
  const validIndex = Math.max(0, Math.min(safeVisits.length - 1, featuredIndex));
  const featured = safeVisits[validIndex] || safeVisits[0] || {};

  worldVisits[countryCode] = {
    ...existing,
    status: existing.status || 'visited',
    featuredVisitIndex: validIndex,
    visits: safeVisits,
    entryDate: featured.entryDate || existing.entryDate || '',
    entryTransport: featured.entryTransport || existing.entryTransport || 'flight',
    exitDate: featured.exitDate !== undefined ? featured.exitDate : (existing.exitDate || ''),
    exitTransport: featured.exitTransport !== undefined ? featured.exitTransport : (existing.exitTransport || 'flight'),
    buddies: Array.isArray(featured.buddies) ? featured.buddies : (existing.buddies || []),
    date: featured.entryDate || existing.date || new Date().toISOString().split('T')[0]
  };

  safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(worldVisits));
  notifyStateChange();
  return worldVisits[countryCode];
}

export function setCountryFeaturedVisit(countryCode, featuredIndex) {
  const visits = getCountryVisits(countryCode);
  if (visits.length === 0) return;
  return saveCountryVisits(countryCode, visits, featuredIndex);
}

export function toggleWorldCity(countryCode, cityName, isVisited, notes = '') {
  let { worldCities, worldVisits } = getStorageData();
  
  if (isVisited) {
    const exists = worldCities.some(c => c.countryCode === countryCode && c.cityName.toLowerCase() === cityName.toLowerCase());
    if (!exists) {
      worldCities.push({ countryCode, cityName, date: new Date().toISOString().split('T')[0], notes: cleanNote(notes) });
    }
    // Auto-mark country as visited if not already
    if (!worldVisits[countryCode] || worldVisits[countryCode].status !== 'visited') {
      worldVisits[countryCode] = {
        ...(worldVisits[countryCode] || {}),
        status: 'visited',
        date: new Date().toISOString().split('T')[0],
        notes: cleanNote(worldVisits[countryCode]?.notes)
      };
      safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(worldVisits));
    }
    triggerConfetti();
  } else {
    worldCities = worldCities.filter(c => !(c.countryCode === countryCode && c.cityName.toLowerCase() === cityName.toLowerCase()));
  }

  safeSetItem(STORAGE_KEYS.WORLD_CITIES, JSON.stringify(worldCities));
  notifyStateChange();
}

export function triggerConfetti() {
  try {
    if (typeof window !== 'undefined') {
      window.__confettiCount = (window.__confettiCount || 0) + 1;
    }
    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.7 }
    });
  } catch (e) {
    // Ignore if canvas confetti not active
  }
}

export function calculateStats() {
  const { turkeyVisits, worldVisits, worldCities } = getStorageData();

  // Turkey stats
  const turkeyVisitedIds = Object.keys(turkeyVisits).filter(id => turkeyVisits[id].status === 'visited');
  const turkeyTargetIds = Object.keys(turkeyVisits).filter(id => turkeyVisits[id].status === 'target');
  const turkeyCount = turkeyVisitedIds.length;
  const turkeyPercentage = ((turkeyCount / 81) * 100).toFixed(1);

  // Region breakdown
  const regionCounts = {};
  TURKEY_PROVINCES.forEach(p => {
    if (turkeyVisits[p.id]?.status === 'visited') {
      regionCounts[p.region] = (regionCounts[p.region] || 0) + 1;
    }
  });

  // World stats
  const worldVisitedCodes = Object.keys(worldVisits).filter(code => !code.includes('::') && worldVisits[code]?.status === 'visited');
  const worldTargetCodes = Object.keys(worldVisits).filter(code => !code.includes('::') && (worldVisits[code]?.status === 'planned' || worldVisits[code]?.status === 'target'));
  
  // Include Turkey in worldVisitedCodes if at least 1 Turkish province is visited
  if (turkeyCount > 0 && !worldVisitedCodes.includes('TR')) {
    worldVisitedCodes.push('TR');
  }

  const worldCountryCount = worldVisitedCodes.length;
  const worldPercentage = ((worldCountryCount / TOTAL_WORLD_COUNTRIES_BENCHMARK) * 100).toFixed(1);

  // Continent breakdown
  const continentCounts = {};
  WORLD_COUNTRIES.forEach(c => {
    if (worldVisits[c.code]?.status === 'visited' || (c.code === 'TR' && turkeyCount > 0)) {
      continentCounts[c.continent] = (continentCounts[c.continent] || 0) + 1;
    }
  });

  const markedRegionCount = Object.keys(worldVisits).filter(code => code.includes('::') && worldVisits[code]?.status === 'visited').length;
  const worldCityCount = Math.max(worldCities.length, markedRegionCount) + turkeyCount;

  // Global Demographic & Land Impact
  const demographicStats = calculateDemographicImpact(worldVisitedCodes);

  return {
    turkeyCount,
    turkeyTargetCount: turkeyTargetIds.length,
    turkeyPercentage,
    regionCounts,
    worldCountryCount,
    worldTargetCount: worldTargetCodes.length,
    worldPercentage,
    continentCounts,
    worldCityCount,
    totalPlacesMarked: turkeyCount + worldCountryCount,
    landAreaKm2: demographicStats.totalAreaKm2,
    landAreaPercent: demographicStats.landAreaPercent,
    populationCount: demographicStats.totalPopCount,
    populationPercent: demographicStats.populationPercent
  };
}

export function exportBackup() {
  const data = getStorageData();
  let userProfile = null;
  try {
    const raw = localStorage.getItem('gv_profile');
    if (raw) userProfile = JSON.parse(raw);
  } catch {}

  const backupPayload = {
    ...data,
    profile: userProfile || data.userProfile,
    userProfile: userProfile || data.userProfile,
    userAirlines: getUserAirlines(),
    userAircraft: getUserAircraft(),
    bucketRanks: getBucketRanks(),
    savedFriends: getSavedFriends(),
    userFeedbacks: getUserFeedbacks(),
    feedbackOverrides: getFeedbackStatusOverrides(),
    homeCountry: getHomeCountry(),
    exportedAt: new Date().toISOString()
  };
  const jsonStr = JSON.stringify(backupPayload, null, 2);
  if (typeof document !== 'undefined' && typeof Blob !== 'undefined' && typeof URL !== 'undefined' && URL.createObjectURL) {
    try {
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `gittigim-yerler-yedek-${new Date().toISOString().split('T')[0]}.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {}
  }
  return jsonStr;
}

export function resetTravelData() {
  localStorage.removeItem(STORAGE_KEYS.TURKEY_VISITS);
  localStorage.removeItem(STORAGE_KEYS.WORLD_VISITS);
  localStorage.removeItem(STORAGE_KEYS.WORLD_CITIES);
  localStorage.removeItem('gv_unlocked_achievements');
  localStorage.removeItem(STORAGE_KEYS.BUCKET_RANKS);
  localStorage.removeItem(STORAGE_KEYS.USER_AIRLINES);
  localStorage.removeItem(STORAGE_KEYS.USER_AIRCRAFT);
  localStorage.removeItem(STORAGE_KEYS.HOME_COUNTRY);
  unlockedCache = [];
  notifyStateChange();
}

export function importBackup(fileContent) {
  try {
    const data = JSON.parse(fileContent);
    if (data.turkeyVisits) safeSetItem(STORAGE_KEYS.TURKEY_VISITS, JSON.stringify(data.turkeyVisits));
    if (data.worldVisits) safeSetItem(STORAGE_KEYS.WORLD_VISITS, JSON.stringify(data.worldVisits));
    if (data.worldCities) safeSetItem(STORAGE_KEYS.WORLD_CITIES, JSON.stringify(data.worldCities));
    const prof = data.profile || data.userProfile;
    if (prof) {
      safeSetItem(STORAGE_KEYS.USER_PROFILE, JSON.stringify(prof));
      safeSetItem('gv_profile', JSON.stringify(prof));
    }
    if (data.userAirlines) safeSetItem(STORAGE_KEYS.USER_AIRLINES, JSON.stringify(data.userAirlines));
    if (data.userAircraft) safeSetItem(STORAGE_KEYS.USER_AIRCRAFT, JSON.stringify(data.userAircraft));
    if (data.bucketRanks) safeSetItem(STORAGE_KEYS.BUCKET_RANKS, JSON.stringify(data.bucketRanks));
    if (data.savedFriends) safeSetItem(STORAGE_KEYS.SAVED_FRIENDS, JSON.stringify(data.savedFriends));
    if (data.userFeedbacks) safeSetItem(STORAGE_KEYS.USER_FEEDBACKS, JSON.stringify(data.userFeedbacks));
    if (data.feedbackOverrides) safeSetItem(STORAGE_KEYS.FEEDBACK_STATUS_OVERRIDES, JSON.stringify(data.feedbackOverrides));
    if (data.homeCountry) setHomeCountry(data.homeCountry);
    notifyStateChange();
    return true;
  } catch (e) {
    if (typeof alert !== 'undefined') alert('Geçersiz yedek dosyası formatı!');
    else console.warn('Geçersiz yedek dosyası formatı:', e);
    return false;
  }
}

import { getEarnedAchievements } from '../data/achievements.js';
import { notifyAchievementUnlocked } from './notifications.js';

// Event system for real-time UI reactive updates
const listeners = [];
export function onStateChange(callback) {
  listeners.push(callback);
}

let unlockedCache = null;
function getUnlockedCache() {
  if (unlockedCache === null) {
    try {
      const raw = localStorage.getItem('gv_unlocked_achievements');
      unlockedCache = raw ? JSON.parse(raw) : [];
    } catch {
      unlockedCache = [];
    }
  }
  return unlockedCache;
}

export function checkAndNotifyAchievements(storageData, baseStats) {
  try {
    const earned = getEarnedAchievements(storageData, baseStats);
    const earnedIds = earned.map(a => a.id);
    const unlocked = getUnlockedCache();

    const newlyUnlocked = earned.filter(a => !unlocked.includes(a.id));
    if (newlyUnlocked.length > 0) {
      newlyUnlocked.forEach(a => {
        notifyAchievementUnlocked(a);
      });
    }

    unlockedCache = earnedIds;
    safeSetItem('gv_unlocked_achievements', JSON.stringify(earnedIds));
  } catch (e) {
    console.error('Achievement check error', e);
  }
}

function notifyStateChange() {
  const sData = getStorageData();
  const sStats = calculateStats();
  checkAndNotifyAchievements(sData, sStats);
  listeners.forEach(cb => cb(sData, sStats));
  try {
    queueCloudSync();
  } catch (e) {
    console.warn('Auto cloud sync trigger error:', e);
  }
}

// ─── Bucket List Priority Rankings ───────────────────────────────────────────
export function getBucketRanks() {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.BUCKET_RANKS);
    const parsed = raw ? JSON.parse(raw) : null;
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveBucketRanks(ranks) {
  try {
    safeSetItem(STORAGE_KEYS.BUCKET_RANKS, JSON.stringify(ranks));
    notifyStateChange();
  } catch (e) {
    console.error('Error saving bucket ranks', e);
  }
}

// ─── User Airlines Tracker ────────────────────────────────────────────────────
export function getUserAirlines() {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.USER_AIRLINES);
    const parsed = raw ? JSON.parse(raw) : null;
    const data = (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) ? parsed : {};
    let changed = false;
    for (const airline of ALL_AIRLINES) {
      if (airline.code && data[airline.id]) {
        const siblings = ALL_AIRLINES.filter(a => a.code === airline.code);
        for (const sib of siblings) {
          if (!data[sib.id]) {
            data[sib.id] = { ...data[airline.id] };
            changed = true;
          }
        }
      }
    }
    if (changed) {
      saveUserAirlines(data);
    }
    return data;
  } catch {
    return {};
  }
}

export function saveUserAirlines(airlines) {
  try {
    safeSetItem(STORAGE_KEYS.USER_AIRLINES, JSON.stringify(airlines));
    notifyStateChange();
  } catch (e) {
    console.error('Error saving user airlines', e);
  }
}

export function toggleUserAirline(airlineId, flightsCount = 1) {
  const data = getUserAirlines();
  const currentItem = ALL_AIRLINES.find(a => a.id === airlineId);
  const targetCode = currentItem?.code;

  // Find all airline IDs that represent the same airline (e.g. 'thy' and 'thy_star' for TK)
  const matchingIds = targetCode
    ? ALL_AIRLINES.filter(a => a.code === targetCode).map(a => a.id)
    : [airlineId];

  const willRemove = !!data[airlineId];

  matchingIds.forEach(id => {
    if (willRemove) {
      delete data[id];
    } else {
      data[id] = { flown: true, count: Math.max(1, flightsCount), date: new Date().toISOString().split('T')[0] };
    }
  });

  saveUserAirlines(data);
  return data;
}

// ─── Saved Friends System ─────────────────────────────────────────────────────
export function getSavedFriends() {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.SAVED_FRIENDS);
    const parsed = raw ? JSON.parse(raw) : null;
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveFriend(friendObj) {
  const friends = getSavedFriends();
  const existingIdx = friends.findIndex(f => f.id === friendObj.id || (f.username && f.username.toLowerCase() === friendObj.username.toLowerCase()));
  if (existingIdx >= 0) {
    friends[existingIdx] = { ...friends[existingIdx], ...friendObj, updatedAt: new Date().toISOString() };
  } else {
    friends.push({
      id: friendObj.id || 'f_' + Date.now(),
      username: friendObj.username || 'Arkadaş',
      avatar: friendObj.avatar || '🌍',
      bio: friendObj.bio || '',
      code: friendObj.code || '',
      data: friendObj.data || null,
      savedAt: new Date().toISOString()
    });
  }
  safeSetItem(STORAGE_KEYS.SAVED_FRIENDS, JSON.stringify(friends));
  notifyStateChange();
  return friends;
}

export function deleteFriend(friendId) {
  const friends = getSavedFriends().filter(f => f.id !== friendId);
  safeSetItem(STORAGE_KEYS.SAVED_FRIENDS, JSON.stringify(friends));
  notifyStateChange();
  return friends;
}

// ─── Aircraft Fleet Tracker ──────────────────────────────────────────────────
export function getUserAircraft() {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.USER_AIRCRAFT);
    const parsed = raw ? JSON.parse(raw) : null;
    return (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) ? parsed : {};
  } catch {
    return {};
  }
}

export function saveUserAircraft(aircraft) {
  try {
    safeSetItem(STORAGE_KEYS.USER_AIRCRAFT, JSON.stringify(aircraft));
    notifyStateChange();
  } catch (e) {
    console.error('Error saving user aircraft', e);
  }
}

export function toggleUserAircraft(modelId) {
  const data = getUserAircraft();
  if (data[modelId]) {
    delete data[modelId];
  } else {
    data[modelId] = { flown: true, date: new Date().toISOString().split('T')[0] };
  }
  saveUserAircraft(data);
  return data;
}


// ─── Feedback & Bug Report Tracker ──────────────────────────────────────────
export function getUserFeedbacks() {
  try {
    const rawPrimary = localStorage.getItem(STORAGE_KEYS.USER_FEEDBACKS);
    const rawLegacy = localStorage.getItem('gv_user_feedbacks');
    let feedbacks = [];
    try {
      const listA = rawPrimary ? JSON.parse(rawPrimary) : [];
      const listB = rawLegacy ? JSON.parse(rawLegacy) : [];
      const seen = new Set();
      for (const it of [...listA, ...listB]) {
        if (it && it.id && !seen.has(it.id)) {
          seen.add(it.id);
          feedbacks.push(it);
        }
      }
    } catch {}
    
    // Apply any status overrides (e.g. from developer/admin or shared status)
    const overrides = getFeedbackStatusOverrides();
    return feedbacks.map(fb => {
      if (overrides[fb.id]) {
        return { ...fb, ...overrides[fb.id] };
      }
      return fb;
    });
  } catch {
    return [];
  }
}

export function saveUserFeedback(item) {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.USER_FEEDBACKS);
    const parsed = raw ? JSON.parse(raw) : null;
    let feedbacks = Array.isArray(parsed) ? parsed : [];
    
    const feedbackObj = {
      id: item.id || ('fb_' + Date.now() + '_' + Math.random().toString(36).substring(2, 7)),
      type: item.type || 'suggestion',
      message: item.message || '',
      contact: item.contact || '',
      username: item.username || 'Gezgin',
      status: item.status || 'pending', // pending, considering, in_progress, resolved, declined
      synced: item.synced === true, // true if sent to server, false if offline/pending
      devResponse: item.devResponse || '',
      createdAt: item.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
    
    feedbacks.unshift(feedbackObj);
    safeSetItem(STORAGE_KEYS.USER_FEEDBACKS, JSON.stringify(feedbacks));
    notifyStateChange();
    return feedbackObj;
  } catch (e) {
    console.error('Error saving user feedback', e);
    return item;
  }
}

// Telegram Bot Direct Fallback Credentials
const TELEGRAM_BOT_TOKEN = '8842381582:AAH_tgTR4uAudrcIQ1SCbgRzcear3wfP2cU';
const TELEGRAM_CHAT_ID = '7906240525';

export async function sendFeedbackToTelegramDirect(fb, options = {}) {
  try {
    const typeLabel = fb.type === 'bug' ? '🐞 Hata / Bug' : (fb.type === 'feature' ? '✨ Yeni Özellik İsteği' : '💡 Öneri / Tavsiye');
    const nowStr = new Date().toLocaleString('tr-TR', { timeZone: 'Europe/Istanbul' });
    const createdStr = fb.createdAt ? new Date(fb.createdAt).toLocaleString('tr-TR', { timeZone: 'Europe/Istanbul' }) : nowStr;
    const cleanMsg = String(fb.message || '').trim().slice(0, 1000);
    const cleanContact = fb.contact ? String(fb.contact).trim().slice(0, 120) : 'Belirtilmedi';
    const cleanUsername = fb.username ? String(fb.username).trim().slice(0, 60) : 'Gezgin';
    const cleanId = String(fb.id || ('fb_' + Date.now())).trim().slice(0, 50);

    const esc = (t) => String(t || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

    let headerPrefix = '📬 <b>Yeni Gezgin Bildirimi!</b>';
    if (options.isHistorical || fb.isHistoricalArchive) {
      headerPrefix = '📜 <b>[Geçmiş Bildirim Arşivi - Otomatik İletim]</b>';
    } else if (options.isQueued || fb.synced === false) {
      headerPrefix = '🕒 <b>[Kuyruktan İletildi - Gecikmeli Teslimat]</b>';
    }

    let timeDetails = `🕒 <b>Zaman:</b> ${esc(nowStr)}`;
    if (createdStr && createdStr !== nowStr) {
      timeDetails = `📅 <b>Oluşturulma:</b> ${esc(createdStr)}\n⚡ <b>İletilme:</b> ${esc(nowStr)}`;
    }

    const telegramText = `${headerPrefix}\n\n🆔 <b>ID:</b> <code>${esc(cleanId)}</code>\n🏷️ <b>Tür:</b> ${esc(typeLabel)}\n👤 <b>Kullanıcı:</b> ${esc(cleanUsername)}\n📱 <b>İletişim:</b> ${esc(cleanContact)}\n\n📝 <b>Mesaj:</b>\n${esc(cleanMsg)}\n\n${timeDetails}`;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 12000);

    const res = await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: TELEGRAM_CHAT_ID,
        text: telegramText,
        parse_mode: 'HTML'
      }),
      signal: controller.signal
    });
    clearTimeout(timeoutId);

    const data = await res.json();
    if (data && data.ok) {
      return { ok: true };
    }
    return { ok: false, error: data?.description || 'Telegram reddetti' };
  } catch (err) {
    console.warn('Direct Telegram dispatch error:', err);
    return { ok: false, error: err?.name === 'AbortError' ? 'Zaman aşımı (12s)' : (err?.message || 'Ağ bağlantı hatası') };
  }
}

/**
 * Bekleyen tüm bildirimleri arka planda sessizce ve otomatik olarak Telegram'a aktarır.
 * Hiçbir buton veya kullanıcı müdahalesi gerektirmez.
 */
export async function syncPendingFeedbacks() {
  if (typeof navigator !== 'undefined' && !navigator.onLine) {
    return false;
  }
  try {
    const rawPrimary = localStorage.getItem(STORAGE_KEYS.USER_FEEDBACKS);
    const rawLegacy = localStorage.getItem('gv_user_feedbacks');
    let feedbacks = [];
    try {
      const listA = rawPrimary ? JSON.parse(rawPrimary) : [];
      const listB = rawLegacy ? JSON.parse(rawLegacy) : [];
      const seen = new Set();
      for (const it of [...listA, ...listB]) {
        if (it && it.id && !seen.has(it.id)) {
          seen.add(it.id);
          feedbacks.push(it);
        }
      }
    } catch {}

    if (!Array.isArray(feedbacks) || feedbacks.length === 0) return true;

    // synced değeri true OLMAYAN (false, null, undefined, eski sürümler) her şeyi yakala
    const pending = feedbacks.filter(fb => fb.synced !== true);
    if (pending.length === 0) return true;

    let updated = false;
    for (const fb of pending) {
      let result = await sendFeedbackToTelegramDirect(fb, { isQueued: true });

      // Direct başarısız olursa Vercel sunucusunu dene
      if (!result.ok) {
        try {
          const apiUrl = 'https://gittigim-yerler.vercel.app/api/feedback';
          const res = await fetch(apiUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              id: fb.id,
              type: fb.type,
              message: fb.message,
              contact: fb.contact,
              username: fb.username
            })
          });
          if (res.ok) {
            result = { ok: true };
          }
        } catch {}
      }

      if (result.ok) {
        fb.synced = true;
        fb.syncedAt = new Date().toISOString();
        delete fb.failReason;
        updated = true;
      } else {
        fb.synced = false;
        fb.failReason = result.error || 'İletim hatası';
        updated = true;
      }
    }

    if (updated) {
      safeSetItem(STORAGE_KEYS.USER_FEEDBACKS, JSON.stringify(feedbacks));
      try { localStorage.removeItem('gv_user_feedbacks'); } catch {}
      notifyStateChange();
    }
    return true;
  } catch (e) {
    console.error('Error syncing pending feedbacks', e);
    return false;
  }
}

/**
 * Geçmiş bildirimleri tek seferliğine tespit edip Telegram'a arşiv olarak iletir.
 * 'gv_past_feedbacks_flushed_v2' ile mühürlenir, asla mükerrer gönderim yapmaz.
 */
export async function flushPastFeedbacksOnce() {
  if (typeof window === 'undefined') return;
  try {
    const isFlushed = localStorage.getItem('gv_past_feedbacks_flushed_v2');
    if (isFlushed === 'true') {
      // Zaten geçmiş aktarımı yapılmış, sadece bekleyenleri senkronize et
      syncPendingFeedbacks();
      return;
    }

    // İlk kez çalışıyor: Tüm geçmiş bildirimleri topla
    const rawPrimary = localStorage.getItem(STORAGE_KEYS.USER_FEEDBACKS);
    const rawLegacy = localStorage.getItem('gv_user_feedbacks');
    let feedbacks = [];
    try {
      const listA = rawPrimary ? JSON.parse(rawPrimary) : [];
      const listB = rawLegacy ? JSON.parse(rawLegacy) : [];
      const seen = new Set();
      for (const it of [...listA, ...listB]) {
        if (it && it.id && !seen.has(it.id)) {
          seen.add(it.id);
          feedbacks.push(it);
        }
      }
    } catch {}

    if (feedbacks.length > 0) {
      let count = 0;
      for (const fb of feedbacks) {
        // İletilmemiş olanları arşiv damgasıyla gönder
        if (fb.synced !== true) {
          const res = await sendFeedbackToTelegramDirect(fb, { isHistorical: true });
          if (res.ok) {
            fb.synced = true;
            fb.syncedAt = new Date().toISOString();
            fb.isHistoricalArchive = true;
            delete fb.failReason;
            count++;
          }
        }
      }
      safeSetItem(STORAGE_KEYS.USER_FEEDBACKS, JSON.stringify(feedbacks));
      try { localStorage.removeItem('gv_user_feedbacks'); } catch {}
      console.log(`[Gezgin] Geçmiş ${count} adet bildirim Telegram'a tek seferlik başarıyla aktarıldı.`);
    }

    localStorage.setItem('gv_past_feedbacks_flushed_v2', 'true');
    notifyStateChange();
  } catch (err) {
    console.warn('Flush past feedbacks error:', err);
  }
}

/**
 * Uygulama başlangıcında ve ağ değişikliklerinde otomatik senkronizasyon motorunu başlatır
 */
export function initFeedbackSync() {
  if (typeof window === 'undefined') return;
  setTimeout(() => {
    flushPastFeedbacksOnce();
  }, 1500);

  window.addEventListener('online', () => {
    syncPendingFeedbacks();
  });

  // Her 60 saniyede bir arka planda bekleyen varsa otomatik dene
  setInterval(() => {
    if (navigator.onLine) {
      syncPendingFeedbacks();
    }
  }, 60000);
}

export function getFeedbackStatusOverrides() {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.FEEDBACK_STATUS_OVERRIDES);
    const parsed = raw ? JSON.parse(raw) : null;
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

export function updateFeedbackStatus(id, newStatus, devResponse = '') {
  try {
    const overrides = getFeedbackStatusOverrides();
    overrides[id] = {
      status: newStatus,
      devResponse: devResponse !== undefined ? devResponse : (overrides[id]?.devResponse || ''),
      updatedAt: new Date().toISOString()
    };
    safeSetItem(STORAGE_KEYS.FEEDBACK_STATUS_OVERRIDES, JSON.stringify(overrides));
    
    // Also update directly in user feedbacks if present
    const raw = localStorage.getItem(STORAGE_KEYS.USER_FEEDBACKS);
    const parsed = raw ? JSON.parse(raw) : null;
    let feedbacks = Array.isArray(parsed) ? parsed : [];
    const idx = feedbacks.findIndex(f => f.id === id);
    if (idx !== -1) {
      feedbacks[idx].status = newStatus;
      if (devResponse) feedbacks[idx].devResponse = devResponse;
      feedbacks[idx].updatedAt = new Date().toISOString();
      safeSetItem(STORAGE_KEYS.USER_FEEDBACKS, JSON.stringify(feedbacks));
    }
    
    notifyStateChange();
    return true;
  } catch (e) {
    console.error('Error updating feedback status', e);
    return false;
  }
}

export function deleteUserFeedback(id) {
  try {
    const raw = localStorage.getItem(STORAGE_KEYS.USER_FEEDBACKS);
    const parsed = raw ? JSON.parse(raw) : null;
    let feedbacks = Array.isArray(parsed) ? parsed : [];
    feedbacks = feedbacks.filter(f => f.id !== id);
    safeSetItem(STORAGE_KEYS.USER_FEEDBACKS, JSON.stringify(feedbacks));
    
    // Also clean override if present
    const overrides = getFeedbackStatusOverrides();
    if (overrides[id]) {
      delete overrides[id];
      safeSetItem(STORAGE_KEYS.FEEDBACK_STATUS_OVERRIDES, JSON.stringify(overrides));
    }
    
    notifyStateChange();
    return true;
  } catch (e) {
    console.error('Error deleting feedback', e);
    return false;
  }
}

// ─── Home Country Selection ───────────────────────────────────────────────────
export function getHomeCountry() {
  try {
    return localStorage.getItem(STORAGE_KEYS.HOME_COUNTRY) || 'TR';
  } catch {
    return 'TR';
  }
}

export function setHomeCountry(code) {
  try {
    safeSetItem(STORAGE_KEYS.HOME_COUNTRY, code || 'TR');
  } catch (e) {
    console.warn('Error saving home country', e);
  }
  notifyStateChange();
}

// ─── Passport Type (Bordo / Yesil) ───────────────────────────────────────────
export function getPassportType() {
  try {
    return localStorage.getItem('gv_passport_type') || 'bordo';
  } catch {
    return 'bordo';
  }
}

export function setPassportType(type) {
  try {
    safeSetItem('gv_passport_type', type === 'yesil' ? 'yesil' : 'bordo');
  } catch (e) {
    console.warn('Error saving passport type', e);
  }
  notifyStateChange();
}

// ─── Upcoming Trip Countdown ────────────────────────────────────────────────
export function getUpcomingTrip() {
  try {
    const raw = localStorage.getItem('gv_upcoming_trip');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === 'object' && parsed.destination && parsed.date) {
        return parsed;
      }
    }
  } catch (e) {
    console.warn('Error reading upcoming trip', e);
  }
  return null;
}

export function saveUpcomingTrip(tripData) {
  try {
    if (!tripData) {
      localStorage.removeItem('gv_upcoming_trip');
    } else {
      safeSetItem('gv_upcoming_trip', JSON.stringify(tripData));
    }
  } catch (e) {
    console.warn('Error saving upcoming trip', e);
  }
  notifyStateChange();
}

export function deleteUpcomingTrip() {
  try {
    localStorage.removeItem('gv_upcoming_trip');
  } catch (e) {
    console.warn('Error removing upcoming trip', e);
  }
  notifyStateChange();
}

// ─── Favorite Places / Restaurants / Cafes Tracker ──────────────────────────
export function getAllSavedPlaces() {
  try {
    const { turkeyVisits, worldVisits } = getStorageData();
    const all = [];

    Object.entries(turkeyVisits || {}).forEach(([pid, v]) => {
      if (Array.isArray(v?.places) && v.places.length > 0) {
        v.places.forEach(p => {
          all.push({
            ...p,
            targetId: `TR::${pid}`,
            countryCode: 'TR'
          });
        });
      }
    });

    Object.entries(worldVisits || {}).forEach(([code, v]) => {
      if (Array.isArray(v?.places) && v.places.length > 0) {
        const countryCode = code.includes('::') ? code.split('::')[0] : code;
        v.places.forEach(p => {
          all.push({
            ...p,
            targetId: code,
            countryCode
          });
        });
      }
    });

    return all;
  } catch {
    return [];
  }
}

export function getTotalPlacesCount() {
  return getAllSavedPlaces().length;
}

// ─── User Custom Visa Overrides ─────────────────────────────────────────────
export function getUserVisaOverrides() {
  try {
    const raw = localStorage.getItem('gv_visa_overrides');
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

export function getUserVisaOverride(countryCode) {
  if (!countryCode) return null;
  const overrides = getUserVisaOverrides();
  return overrides[countryCode.toUpperCase()] || null;
}

export function setUserVisaOverride(countryCode, visaStatus) {
  if (!countryCode) return;
  try {
    const code = countryCode.toUpperCase();
    const overrides = getUserVisaOverrides();
    if (!visaStatus) {
      delete overrides[code];
    } else {
      overrides[code] = visaStatus; // 'vizesiz' | 'vize' | 'kapida_vize' | 'e_vize'
    }
    safeSetItem('gv_visa_overrides', JSON.stringify(overrides));
  } catch (e) {
    console.warn('Error saving visa override', e);
  }
  notifyStateChange();
}

// ─── User Personal Visa Records ──────────────────────────────────────────────

/**
 * All 29 Schengen Area member states.
 * A single Schengen visa covers all of these countries.
 */
export const SCHENGEN_COUNTRIES = [
  'AT', 'BE', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU',
  'IS', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT',
  'SK', 'SI', 'ES', 'SE', 'CH', 'LI', 'HR', 'BG', 'RO', 'CY'
];

/**
 * Visa type → covered country codes mapping.
 */
export const VISA_COVERAGE_MAP = {
  schengen: ['AT', 'BE', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU',
             'IS', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT',
             'SK', 'SI', 'ES', 'SE', 'CH', 'LI', 'HR', 'BG', 'RO', 'CY'],
  us: ['US'],
  uk: ['GB'],
  canada: ['CA'],
  japan: ['JP'],
  australia: ['AU'],
  uae: ['AE'],
  other: []
};

/**
 * Returns all user-entered visa records.
 * @returns {Array}
 */
export function getUserVisas() {
  try {
    const raw = localStorage.getItem('gv_user_visas_v1');
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

/**
 * Saves a visa record. Updates if id matches, otherwise creates new.
 * @param {Object} visaData
 */
export function saveUserVisa(visaData) {
  try {
    let visas = getUserVisas();
    if (visaData.id) {
      const idx = visas.findIndex(v => v.id === visaData.id);
      if (idx >= 0) {
        visas[idx] = { ...visas[idx], ...visaData, updatedAt: new Date().toISOString() };
      } else {
        visas.push({ ...visaData, updatedAt: new Date().toISOString() });
      }
    } else {
      const newVisa = {
        ...visaData,
        id: 'visa_' + Date.now() + '_' + Math.random().toString(36).slice(2, 7),
        createdAt: new Date().toISOString()
      };
      visas.push(newVisa);
    }
    safeSetItem('gv_user_visas_v1', JSON.stringify(visas));
    notifyStateChange();
  } catch (e) {
    console.warn('Error saving visa:', e);
  }
}

/**
 * Deletes a visa record by id.
 * @param {string} visaId
 */
export function deleteUserVisa(visaId) {
  try {
    let visas = getUserVisas().filter(v => v.id !== visaId);
    safeSetItem('gv_user_visas_v1', JSON.stringify(visas));
    notifyStateChange();
  } catch (e) {
    console.warn('Error deleting visa:', e);
  }
}

/**
 * Returns only visas currently active (today within validFrom..validUntil).
 * @returns {Array}
 */
export function getActiveVisas() {
  const today = new Date().toISOString().split('T')[0];
  return getUserVisas().filter(v => {
    // A visa is active if it has not expired (i.e. validUntil is today or in future, or not set)
    if (v.validUntil && today > v.validUntil) return false;
    return true;
  });
}

/**
 * Returns visa coverage info for a specific country.
 * Checks if user has an active visa covering countryCode.
 * @param {string} countryCode - ISO 3166-1 alpha-2
 * @returns {Object|null} visa object or null
 */
export function getVisaCoverageForCountry(countryCode) {
  if (!countryCode) return null;
  const code = countryCode.toUpperCase().trim();
  const countryAliases = {
    DE: ['DE', 'DEU', 'DEUTSCHLAND', 'ALMANYA', 'GERMANY'],
    US: ['US', 'USA', 'UNITED STATES', 'AMERIKA', 'AMERİKA'],
    GB: ['GB', 'GBR', 'UK', 'UNITED KINGDOM', 'İNGİLTERE', 'INGILTERE'],
    FR: ['FR', 'FRA', 'FRANCE', 'FRANSA'],
    IT: ['IT', 'ITA', 'ITALY', 'İTALYA', 'ITALYA'],
    ES: ['ES', 'ESP', 'SPAIN', 'İSPANYA', 'ISPANYA'],
    GR: ['GR', 'GRC', 'GREECE', 'YUNANİSTAN', 'YUNANISTAN'],
    NL: ['NL', 'NLD', 'NETHERLANDS', 'HOLLANDA'],
    JP: ['JP', 'JPN', 'JAPAN', 'JAPONYA'],
    CA: ['CA', 'CAN', 'CANADA', 'KANADA'],
    AE: ['AE', 'ARE', 'UAE', 'BAE', 'UNITED ARAB EMIRATES'],
    AU: ['AU', 'AUS', 'AUSTRALIA', 'AVUSTRALYA']
  };

  for (const visa of getActiveVisas()) {
    const type = (visa.visaType || '').toLowerCase();
    const coverage = VISA_COVERAGE_MAP[type] || [];
    if (coverage.includes(code)) return visa;
    if (visa.singleCountry && visa.singleCountry.toUpperCase().trim() === code) return visa;
    
    // Check issuing country matches this country or alias
    if (visa.issuingCountry) {
      const issuing = visa.issuingCountry.toUpperCase().trim();
      if (issuing === code) return visa;
      const aliases = countryAliases[code];
      if (aliases && aliases.some(a => issuing === a || issuing.startsWith(a))) return visa;
    }
  }
  return null;
}

/**
 * Generates a realistic-looking visa number for the given type.
 * @param {string} visaType
 * @param {string} issuingCountry ISO-3 code (e.g. 'DEU')
 * @returns {string}
 */
export function generateVisaNumber(visaType, issuingCountry) {
  const prefixMap = {
    schengen: (issuingCountry || 'DEU').toUpperCase().slice(0, 3),
    us: 'USA', uk: 'GBR', canada: 'CAN', japan: 'JPN',
    australia: 'AUS', uae: 'UAE',
    other: (issuingCountry || 'OTH').toUpperCase().slice(0, 3)
  };
  const prefix = prefixMap[visaType] || 'OTH';
  return prefix + String(Math.floor(10000000 + Math.random() * 89999999));
}
